# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Chat.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self, client, _id):
        self.Client = client
        self._id = _id
    def setTab(self, MainWindow, ID):
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-4, 9, 811, 561))
        self.tabWidget.setObjectName("tabWidget" + ID)
        self.tabs.append(QtWidgets.QWidget())
        self.tabs[-1].setObjectName(ID)
        self.listWidgets.append(QtWidgets.QListWidget(self.tabs[-1]))
        self.listWidgets[-1].setGeometry(QtCore.QRect(0, 0, 801, 501))
        self.listWidgets[-1].setObjectName("list" + ID)
        self.lineEdits.append(QtWidgets.QLineEdit(self.tabs[-1]))
        self.lineEdits[-1].setGeometry(QtCore.QRect(20, 500, 511, 23))
        self.lineEdits[-1].setObjectName("lineEdit")
        self.pushButtons.append(QtWidgets.QPushButton(self.tabs[-1]))
        self.pushButtons[-1].setGeometry(QtCore.QRect(530, 500, 111, 23))
        self.pushButtons[-1].setObjectName("pushButton")
        self.tabWidget.addTab(self.tabs[-1], ID)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabs[-1]), _translate("MainWindow", "ID"))
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-4, 9, 811, 561))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.listWidget = QtWidgets.QListWidget(self.tab)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 801, 501))
        self.listWidget.setObjectName("listWidget")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(20, 500, 511, 23))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(530, 500, 111, 23))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow, ID):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Sent"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", self._id ))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
